quarkus:
  log:
    level: info
  http:
    access-log:
      enabled: true
  mongodb:
    devservices:
      properties:
        uuidRepresentation: STANDARD
#  mongodb:
#    connection-string: mongodb://localhost:27017/?uuidRepresentation=STANDARD