# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # docker_layer_caching: true
      # specify the version you desire here
      - image: circleci/openjdk:11.0.3-jdk-stretch
      #- image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    branches:
      only:
        - master

    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

      - setup_remote_docker:
          - docker_layer_caching: true

      - run: ./gradlew test

      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

      - store_test_results:
          path: build/test-results/test

      - store_artifacts:
          path: build/test-results/test
          when: always

      - run:
          name: "Build docker image"
          command: docker build -t klubi-api:$CIRCLE_SHA1 .

      - run:
          name: "Publish to image repository"
          command: |
            echo $CR_PASS | docker login -u $CR_USER --password-stdin docker.pkg.github.com
            docker tag klubi-api:$CIRCLE_SHA1 docker.pkg.github.com/pschmidt88/klubi-api/api:$CIRCLE_SHA1
            docker tag klubi-api:$CIRCLE_SHA1 docker.pkg.github.com/pschmidt88/klubi-api/api:$CIRCLE_BUILD_NUM
            docker push docker.pkg.github.com/pschmidt88/klubi-api/api:$CIRCLE_SHA1
            docker push docker.pkg.github.com/pschmidt88/klubi-api/api:$CIRCLE_BUILD_NUM
