# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

jobs:
  build:
    machine: true

    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

    steps:
      - checkout

      - run:
          name: Install openjdk-11-jdk
          command: |
            sudo add-apt-repository ppa:openjdk-r/ppa
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk
            sudo update-java-alternatives --set java-1.11.0-openjdk-amd64

      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

      - run: ./gradlew test

      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

      - store_test_results:
          path: build/test-results/test

      - store_artifacts:
          path: build/test-results/test
          when: always

      - run:
          name: "Build docker image"
          command: docker build -t klubi-api:$CIRCLE_SHA1 .

      - run:
          name: "Publish to image repository"
          command: |
            echo $CR_PASS | docker login -u $CR_USER --password-stdin docker.pkg.github.com
            docker tag klubi-api:$CIRCLE_SHA1 docker.pkg.github.com/pschmidt88/klubi-api/api:$CIRCLE_SHA1
            docker tag klubi-api:$CIRCLE_SHA1 docker.pkg.github.com/pschmidt88/klubi-api/api:$CIRCLE_BUILD_NUM
            docker push docker.pkg.github.com/pschmidt88/klubi-api/api:$CIRCLE_SHA1
            docker push docker.pkg.github.com/pschmidt88/klubi-api/api:$CIRCLE_BUILD_NUM
