name: Klubi API

mongoDbConnection: ${MONGO_DB_CONNECTION}

logging:
  loggers:
    "org.mongodb.driver.cluster": WARN
  appenders:
  - type: console
    threshold: DEBUG
  - type: gelf
    host: ${SEMATEXT_LOG_URL}/klubi-api/
    facility: KlubiAPI
    extractStackTrace: true
    filterStackTrace: true
    includeFullMDC: true
    includeLocation: true
